# Generated by Django 4.0.3 on 2022-12-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerVO',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='SalesPersonVO',
            new_name='SalesPerson',
        ),
    ]
