# Generated by Django 4.0.3 on 2022-12-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
